# Generated by Django 3.2.7 on 2021-09-10 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socialaccount', '0004_auto_20210903_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_layer', models.TextField(max_length=10)),
                ('second_layer', models.TextField(max_length=10)),
                ('third_layer', models.TextField(max_length=10)),
                ('fourth_layer', models.TextField(max_length=10)),
                ('category', models.CharField(blank=True, max_length=1)),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='socialaccount.socialaccount')),
            ],
        ),
    ]
