# Generated by Django 3.2.7 on 2021-09-03 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_layer', models.TextField(max_length=10)),
                ('second_layer', models.TextField(max_length=10)),
                ('third_layer', models.TextField(max_length=10)),
                ('fourth_layer', models.TextField(max_length=10)),
                ('categoty', models.CharField(blank=True, max_length=1)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('verified', models.BooleanField(default=False)),
                ('city', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.city')),
            ],
        ),
    ]
