# Generated by Django 3.2.7 on 2021-09-04 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.RenameField(
            model_name='city',
            old_name='categoty',
            new_name='category',
        ),
    ]
