# Generated by Django 3.2.7 on 2021-09-06 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0004_auto_20210903_1823'),
        ('users', '0003_rename_user_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='socialaccount.socialaccount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdata',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.city'),
        ),
    ]
